openapi: 3.0.3
info:
  title: Entity Type
  version: 1.0.0
  contact: {}
servers:
- url: https://api.airtable.com
paths:
  /v0/appbwEw7nTI2mlYX7/tbltzXpPRPXXgfw7k:
    get:
      summary: Search Entity Types
      description: This searches for valid entity type record IDs
      parameters:
      - name: filterByFormula
        in: query
        schema:
          type: string
          example: SEARCH("Hospital",{Entity Type})
      responses:
        '200':
          description: ''
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags: []
