openapi: 3.0.3
info:
  title: Place of Service
  version: 1.0.0
  contact: {}
servers:
- url: https://api.airtable.com
paths:
  /v0/appbwEw7nTI2mlYX7/tbloZTHS5lnt8InkE:
    get:
      summary: Search Place of Service
      description: This searches for valid place of service record IDs
      parameters:
      - name: filterByFormula
        in: query
        schema:
          type: string
          example: SEARCH("Hospital ER",{Place of Service})
      responses:
        '200':
          description: ''
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags: []
