openapi: 3.0.3
info:
  title: Procedure codes
  version: 1.0.0
  contact: {}
servers:
- url: https://api.airtable.com
paths:
  /v0/appbwEw7nTI2mlYX7/tbl6Krx4apSwhVvyF:
    get:
      summary: Search Procedure codes
      description: This searches for procedure descriptions
      parameters:
      - name: filterByFormula
        in: query
        schema:
          type: string
          example: SEARCH("Colonoscopy",{Procedure Code Full Description})
      responses:
        '200':
          description: ''
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags: []
